const { test, expect,page } = require('@playwright/test');
import { globalSetup } from "../global-setup/globalSetup.js";
import { PageObject } from '../page-factory/page';
import{ ThreePointPageObject} from '../page-factory/threePointShader';
import{ FourPointPageObject} from '../page-factory/fourPointShader';
import{ CurvyProductionPageObject} from '../page-factory/curvyproduction';
const data = require('../testdata/data');


var environment = globalSetup();
var pageObject;
var threePointPageObject;
var fourPointPageObject;
var curvyProductionPageObject;

test.beforeEach(async ({ page }) => {
   pageObject = new PageObject(page);
   threePointPageObject = new ThreePointPageObject(page);
   fourPointPageObject = new FourPointPageObject(page);
   curvyProductionPageObject = new CurvyProductionPageObject(page);
  });


  test('Plotting a Curvy Production Possibility with checking footprint and Check for its exact presence in all the modes', async ({ page }) => {
    await pageObject.launchApplication(environment.baseUrl);
    await pageObject.clickOnLoadAPIButton();
    await threePointPageObject.clickOnOptionButton('Curvy Production Possibility');
    await threePointPageObject.plotshaderOnGraph("Curvy Production Possibility");
    await page.waitForTimeout(3000);
    await page.frameLocator(pageObject.grapfIframe).locator('.form-control').nth(1).fill("30");
  await page.frameLocator(pageObject.grapfIframe).locator('.form-control').nth(2).fill("30");
  await page.frameLocator(pageObject.grapfIframe).locator('.form-control').nth(2).evaluate(e => e.blur());
  var qpoints = await threePointPageObject.getPolygonAttributeByLocator("d",curvyProductionPageObject.curve_Whole);
  
  await page.waitForTimeout(3000);
  await page.frameLocator(pageObject.grapfIframe).locator(threePointPageObject.solutionviewtab).click(); 
  var spoints = await threePointPageObject.getPolygonAttributeByLocator("d",curvyProductionPageObject.curve_Whole);
  
  expect (qpoints).toStrictEqual(spoints);
  await page.waitForTimeout(2000);
  await threePointPageObject.clickOnOptionButton('Curvy Production Possibility');
  await threePointPageObject.plotshaderOnGraph("Curvy Production Possibility");
  await page.waitForTimeout(3000);
  await page.frameLocator(pageObject.grapfIframe).locator('.form-control').nth(1).fill("80");
  await page.frameLocator(pageObject.grapfIframe).locator('.form-control').nth(2).fill("80");
  await page.frameLocator(pageObject.grapfIframe).locator('.form-control').nth(5).fill("90");
  await page.frameLocator(pageObject.grapfIframe).locator('.form-control').nth(6).fill("90");
  await page.frameLocator(pageObject.grapfIframe).locator('.form-control').nth(6).evaluate(e => e.blur());
  await expect(page.frameLocator(pageObject.grapfIframe).locator(curvyProductionPageObject.curve_Whole)).toBeVisible();
  await expect(page.frameLocator(pageObject.grapfIframe).locator(curvyProductionPageObject.curve_Sol)).toBeVisible();
  await expect(page.frameLocator(pageObject.grapfIframe).locator(curvyProductionPageObject.curve_Footprint)).toBeVisible();
  var fpoints = await threePointPageObject.getPolygonAttributeByLocator("d",curvyProductionPageObject.curve_Footprint);
  var apoints = await threePointPageObject.getPolygonAttributeByLocator("d",curvyProductionPageObject.curve_Sol);
  await page.frameLocator(pageObject.grapfIframe).locator(threePointPageObject.closebutton).nth(0).click();
  await page.frameLocator('iframe[name="ext_012345678_1"]').locator('text=accordion-closeGraph Description >> button').click();
  await page.frameLocator(pageObject.grapfIframe).locator(threePointPageObject.link_Generate).click();
  await page.frameLocator(pageObject.grapfIframe).locator(threePointPageObject.btn_Save).click();
  await page.locator(threePointPageObject.retrieveoutput).click();
  await page.locator(threePointPageObject.modedropdown).selectOption('preview');
  await page.locator(threePointPageObject.copytoinput).click();
  await pageObject.clickOnLoadAPIButton();
  await page.waitForTimeout(3000);
  await expect(page.frameLocator(pageObject.grapfIframe).locator(curvyProductionPageObject.curve_Whole)).toBeVisible();
  await expect(page.frameLocator(pageObject.grapfIframe).locator(curvyProductionPageObject.curve_Sol)).toBeVisible();
  await expect(page.frameLocator(pageObject.grapfIframe).locator(curvyProductionPageObject.curve_Footprint)).toBeVisible();
  var s1points = await threePointPageObject.getPolygonAttributeByLocator("d",curvyProductionPageObject.curve_Whole);
  var a1points = await threePointPageObject.getPolygonAttributeByLocator("d",curvyProductionPageObject.curve_Sol);
  var f1points = await threePointPageObject.getPolygonAttributeByLocator("d",curvyProductionPageObject.curve_Footprint);
  expect (s1points).toStrictEqual(spoints);
  expect (a1points).toStrictEqual(apoints);
  expect (f1points).toStrictEqual(fpoints);
  await page.locator(threePointPageObject.modedropdown).selectOption('test');
  await pageObject.clickOnLoadAPIButton();
  await page.waitForTimeout(2000);
  await expect(page.frameLocator(pageObject.grapfIframe).locator(curvyProductionPageObject.curve_Whole)).toBeVisible();
  await expect(page.frameLocator(pageObject.grapfIframe).locator(curvyProductionPageObject.curve_Ans)).toBeVisible();
  var s2points = await threePointPageObject.getPolygonAttributeByLocator("d",curvyProductionPageObject.curve_Whole);
  var q2points = await threePointPageObject.getPolygonAttributeByLocator("d",curvyProductionPageObject.curve_Ans);
  await(page.frameLocator(threePointPageObject. whole_Iframe).locator(curvyProductionPageObject.curvetext_btn)).click();
  await page.waitForTimeout(3000);
  await page.frameLocator(pageObject.grapfIframe).locator('.form-control').nth(5).fill("");
    await page.frameLocator(pageObject.grapfIframe).locator('.form-control').nth(6).fill("");
    
    await expect(page.frameLocator(pageObject.grapfIframe).locator(curvyProductionPageObject.curve_Footprint)).toBeVisible();
    var f2points = await threePointPageObject.getPolygonAttributeByLocator("d",curvyProductionPageObject.curve_Footprint);
    expect (f2points).toStrictEqual(fpoints);
    await page.locator(threePointPageObject.retrieveoutput).click();
    expect (page.locator(threePointPageObject.score_area)).toHaveValue('0');
    await page.waitForTimeout(4000);
    await page.locator(threePointPageObject.copytoinput).click();
    await page.locator(threePointPageObject.modedropdown).selectOption('sample');
    await pageObject.clickOnLoadAPIButton();
    await page.waitForTimeout(3000);
    await expect(page.frameLocator(pageObject.grapfIframe).locator(curvyProductionPageObject.curve_Whole)).toBeVisible();
    var ppoints = await threePointPageObject.getPolygonAttributeByLocator("d",curvyProductionPageObject.curve_Whole);
    await expect(page.frameLocator(pageObject.grapfIframe).locator(curvyProductionPageObject.curve_Ans)).toBeVisible();
    var a3points = await threePointPageObject.getPolygonAttributeByLocator("d",curvyProductionPageObject.curve_Ans);
    await expect(page.frameLocator(pageObject.grapfIframe).locator(curvyProductionPageObject.curve_Footprint)).toBeVisible();
    var f3points = await threePointPageObject.getPolygonAttributeByLocator("d",curvyProductionPageObject.curve_Footprint);
    expect (f3points).toStrictEqual(fpoints);
    expect (ppoints).toStrictEqual(spoints);
    expect (a3points).not.toEqual(apoints);
    await page.waitForTimeout(2000);
    expect(page.frameLocator(threePointPageObject. whole_Iframe).locator(threePointPageObject.txt_alert)).toBeVisible();
     const receivedalertmsg =await page.frameLocator(threePointPageObject. whole_Iframe).locator(threePointPageObject.txt_alert).allTextContents();
     console.log(receivedalertmsg);
     const expalertsmsg = ["ImportantAnswer is complete but not entirely correct"];
     expect(receivedalertmsg).toStrictEqual(expalertsmsg);
     await page.waitForTimeout(5000);
     expect(page.frameLocator(threePointPageObject. whole_Iframe).locator(threePointPageObject.txt_Incorrect)).toBeVisible();
     expect(page.frameLocator(threePointPageObject. whole_Iframe).locator(threePointPageObject.pregrade_Icon)).toBeVisible();
     expect(page.frameLocator(threePointPageObject. whole_Iframe).locator(threePointPageObject.pregrade_Text)).toBeVisible();
     await (page.frameLocator(threePointPageObject. whole_Iframe).locator(threePointPageObject.pregrade_Text)).click();
     expect(page.frameLocator(threePointPageObject. whole_Iframe).locator(curvyProductionPageObject.Coordinate_txt)).toBeVisible();
     expect(page.frameLocator(threePointPageObject. whole_Iframe).locator(curvyProductionPageObject.txt_Pt1_of_2)).toBeVisible();
    expect(page.frameLocator(threePointPageObject. whole_Iframe).locator(curvyProductionPageObject.txt_Pt2_of_2)).toBeVisible();
     expect(page.frameLocator(pageObject.grapfIframe).locator('.form-control').nth(0)).toBeVisible();
    expect(page.frameLocator(pageObject.grapfIframe).locator('.form-control').nth(1)).toBeVisible();
    expect(page.frameLocator(pageObject.grapfIframe).locator('.form-control').nth(2)).toBeVisible();
    expect(page.frameLocator(pageObject.grapfIframe).locator('.form-control').nth(3)).toBeVisible();
    expect(page.frameLocator(pageObject.grapfIframe).locator('.form-control').nth(0)).toBeDisabled();
    expect(page.frameLocator(pageObject.grapfIframe).locator('.form-control').nth(1)).toBeDisabled();
    expect(page.frameLocator(pageObject.grapfIframe).locator('.form-control').nth(2)).toBeDisabled();
    expect(page.frameLocator(pageObject.grapfIframe).locator('.form-control').nth(3)).toBeDisabled();
    await page.waitForTimeout(4000);
    expect(page.frameLocator(pageObject.grapfIframe).locator('.form-control').nth(1)).toHaveValue("80");
    expect(page.frameLocator(pageObject.grapfIframe).locator('.form-control').nth(2)).toHaveValue("80");
    await page.waitForTimeout(4000);
    await page.frameLocator(pageObject.grapfIframe).locator(curvyProductionPageObject.close_btn).click();
  


    await page.locator(threePointPageObject.modedropdown).selectOption('review');
    await pageObject.clickOnLoadAPIButton();
    await page.waitForTimeout(3000);
    await expect(page.frameLocator(pageObject.grapfIframe).locator(curvyProductionPageObject.curve_Whole)).toBeVisible();
    var p1points = await threePointPageObject.getPolygonAttributeByLocator("d",curvyProductionPageObject.curve_Whole);
    await expect(page.frameLocator(pageObject.grapfIframe).locator(curvyProductionPageObject.curve_Ans)).toBeVisible();
    var a4points = await threePointPageObject.getPolygonAttributeByLocator("d",curvyProductionPageObject.curve_Ans);
    expect (p1points).toStrictEqual(spoints);
    expect (a4points).not.toEqual(apoints);
    await expect(page.frameLocator(pageObject.grapfIframe).locator(curvyProductionPageObject.curve_Footprint)).toBeVisible();
    var f4points = await threePointPageObject.getPolygonAttributeByLocator("d",curvyProductionPageObject.curve_Footprint);
    expect (f4points).toStrictEqual(fpoints);
    expect(page.frameLocator(threePointPageObject. whole_Iframe).locator(threePointPageObject.txt_Incorrect)).toBeVisible();
    expect(page.frameLocator(threePointPageObject. whole_Iframe).locator(threePointPageObject.pregrade_Icon)).toBeVisible();
    await page.waitForTimeout(3000);
    expect(page.frameLocator(threePointPageObject. whole_Iframe).locator(threePointPageObject.txt_Incorrect)).toBeVisible();
     expect(page.frameLocator(threePointPageObject. whole_Iframe).locator(threePointPageObject.pregrade_Icon)).toBeVisible();
     expect(page.frameLocator(threePointPageObject. whole_Iframe).locator(threePointPageObject.pregrade_Text)).toBeVisible();
     await (page.frameLocator(threePointPageObject. whole_Iframe).locator(threePointPageObject.pregrade_Text)).click();
     expect(page.frameLocator(threePointPageObject. whole_Iframe).locator(curvyProductionPageObject.Coordinate_txt)).toBeVisible();
     expect(page.frameLocator(threePointPageObject. whole_Iframe).locator(curvyProductionPageObject.txt_Pt1_of_2)).toBeVisible();
    expect(page.frameLocator(threePointPageObject. whole_Iframe).locator(curvyProductionPageObject.txt_Pt2_of_2)).toBeVisible();
     expect(page.frameLocator(pageObject.grapfIframe).locator('.form-control').nth(0)).toBeVisible();
    expect(page.frameLocator(pageObject.grapfIframe).locator('.form-control').nth(1)).toBeVisible();
    expect(page.frameLocator(pageObject.grapfIframe).locator('.form-control').nth(2)).toBeVisible();
    expect(page.frameLocator(pageObject.grapfIframe).locator('.form-control').nth(3)).toBeVisible();
    expect(page.frameLocator(pageObject.grapfIframe).locator('.form-control').nth(0)).toBeDisabled();
    expect(page.frameLocator(pageObject.grapfIframe).locator('.form-control').nth(1)).toBeDisabled();
    expect(page.frameLocator(pageObject.grapfIframe).locator('.form-control').nth(2)).toBeDisabled();
    expect(page.frameLocator(pageObject.grapfIframe).locator('.form-control').nth(3)).toBeDisabled();
    expect(page.frameLocator(pageObject.grapfIframe).locator('.form-control').nth(1)).toHaveValue("80");
    expect(page.frameLocator(pageObject.grapfIframe).locator('.form-control').nth(2)).toHaveValue("80");
    await page.waitForTimeout(4000);
    await page.frameLocator(pageObject.grapfIframe).locator(curvyProductionPageObject.close_btn).click();   

     });