const { test, expect,page } = require('@playwright/test');
import { globalSetup } from "../global-setup/globalSetup.js";
import { PageObject } from '../page-factory/page';
import{ ThreePointPageObject} from '../page-factory/threePointShader';
import{ FourPointPageObject} from '../page-factory/fourPointShader';
import{ CurvyProductionPageObject} from '../page-factory/curvyproduction';
const data = require('../testdata/data');


var environment =globalSetup();
var pageObject;
var threePointPageObject;
var fourPointPageObject;
var curvyProductionPageObject;

test.beforeEach(async ({ page }) => {
   pageObject = new PageObject(page);
   threePointPageObject = new ThreePointPageObject(page);
   fourPointPageObject = new FourPointPageObject(page);
   curvyProductionPageObject = new CurvyProductionPageObject(page);
  });

  test('Using the 4.0 version state in 5.0', async ({ page }) => {
   await pageObject.launchApplication(environment.baseUrl);
   await page.locator(threePointPageObject.inputtextarea).type(data.version4_state1);
   await page.waitForTimeout(12000);
   await page.waitForLoadState("networkidle");
   await pageObject.clickOnLoadAPIButton();    
    expect(page.frameLocator(threePointPageObject.whole_Iframe).locator(threePointPageObject.graph_Heading).nth(0)).toBeVisible();
    expect(page.frameLocator(threePointPageObject.whole_Iframe).locator(threePointPageObject.graph_Heading).nth(0)).toHaveText("Demand for bagels");
    //await page.waitForTimeout(3000);
    expect(page.frameLocator(threePointPageObject.whole_Iframe).locator(threePointPageObject.edit_btn).nth(0)).toBeVisible();
    expect(page.frameLocator(threePointPageObject.whole_Iframe).locator(threePointPageObject.edit_btn).nth(0)).toBeEnabled();
    expect(page.frameLocator(threePointPageObject.whole_Iframe).locator(threePointPageObject.graph_Heading).nth(1)).toHaveText("");
    await page.waitForTimeout(2000);
    expect(page.frameLocator(threePointPageObject.whole_Iframe).locator(threePointPageObject.edit_btn).nth(1)).toBeHidden();
   //  expect(page.frameLocator(threePointPageObject.whole_Iframe).locator(threePointPageObject.edit_btn).nth(1)).toBeEnabled();
    expect(page.frameLocator(threePointPageObject.whole_Iframe).locator(threePointPageObject.graph_Heading).nth(2)).toBeVisible();
    expect(page.frameLocator(threePointPageObject.whole_Iframe).locator(threePointPageObject.graph_Heading).nth(2)).toHaveText("Price ($/pack)");
    expect(page.frameLocator(threePointPageObject.whole_Iframe).locator(threePointPageObject.edit_btn).nth(2)).toBeVisible();
    expect(page.frameLocator(threePointPageObject.whole_Iframe).locator(threePointPageObject.edit_btn).nth(2)).toBeEnabled();
    expect(page.frameLocator(threePointPageObject.whole_Iframe).locator(threePointPageObject.graph_Heading).nth(3)).toBeVisible();
    expect(page.frameLocator(threePointPageObject.whole_Iframe).locator(threePointPageObject.graph_Heading).nth(3)).toHaveText("Quantity (1,000s of packs/day)");
    expect(page.frameLocator(threePointPageObject.whole_Iframe).locator(threePointPageObject.edit_btn).nth(3)).toBeVisible();
    expect(page.frameLocator(threePointPageObject.whole_Iframe).locator(threePointPageObject.edit_btn).nth(3)).toBeEnabled();
   await page.frameLocator(threePointPageObject.whole_Iframe).locator(threePointPageObject.attributes_Setup).nth(3).click();
   expect(page.frameLocator(threePointPageObject.whole_Iframe).locator(threePointPageObject.demand_txt)).toHaveText("Demand");
   expect(page.frameLocator(threePointPageObject.whole_Iframe).locator(threePointPageObject.d_txt)).toHaveText("D");
   expect(page.frameLocator(threePointPageObject.whole_Iframe).locator(threePointPageObject.edit_btn).nth(4)).toBeDisabled();
   expect(page.frameLocator(threePointPageObject.whole_Iframe).locator(threePointPageObject.edit_btn).nth(5)).toBeEnabled();
   expect(page.frameLocator(threePointPageObject.whole_Iframe).locator(threePointPageObject.lock_btn).nth(0)).toBeDisabled();
   expect(page.frameLocator(threePointPageObject.whole_Iframe).locator(threePointPageObject.lock_btn).nth(1)).toBeEnabled();
   expect(page.frameLocator(threePointPageObject.whole_Iframe).locator(threePointPageObject.delete_btn).nth(0)).toBeDisabled();
   expect(page.frameLocator(threePointPageObject.whole_Iframe).locator(threePointPageObject.delete_btn).nth(1)).toBeEnabled();
   await page.frameLocator(threePointPageObject.whole_Iframe).locator(threePointPageObject.edit_btn).nth(5).click();
   expect (page.frameLocator(threePointPageObject.whole_Iframe).locator(threePointPageObject.properties_Panel).nth(0)).toBeVisible();
   await page.waitForTimeout(3000);
   // const bothIframes = page.frameLocator(threePointPageObject.whole_Iframe).frameLocator(threePointPageObject.txtIframe);
   // await page.waitForTimeout(3000);
   // const originalText =  await bothIframes.locator(threePointPageObject.tinymce).allTextContents();
   // expect(originalText).toStrictEqual("D");
 //  await page.waitForTimeout(3000);
 expect(page.frameLocator(threePointPageObject.whole_Iframe).locator('.form-control').nth(0)).toHaveValue("17");
 expect(page.frameLocator(threePointPageObject.whole_Iframe).locator('.form-control').nth(1)).toHaveValue("1");
 expect(page.frameLocator(threePointPageObject.whole_Iframe).locator(threePointPageObject.Label_txt)).toBeVisible();
 expect(page.frameLocator(threePointPageObject.whole_Iframe).locator(threePointPageObject.Label)).toBeVisible();
 expect(page.frameLocator(threePointPageObject.whole_Iframe).locator(threePointPageObject.Label)).toHaveText("Top Left");
 expect(page.frameLocator(threePointPageObject.whole_Iframe).locator(threePointPageObject.graph_Label)).toBeVisible();
 expect(page.frameLocator(threePointPageObject.whole_Iframe).locator(threePointPageObject.graph_Label)).toHaveText("D");
await page.frameLocator(threePointPageObject.whole_Iframe).locator(threePointPageObject.solutionviewtab).click();
expect(page.frameLocator(threePointPageObject.whole_Iframe).locator(threePointPageObject.graph_Heading).nth(0)).toBeVisible();
    expect(page.frameLocator(threePointPageObject.whole_Iframe).locator(threePointPageObject.graph_Heading).nth(0)).toHaveText("Demand for bagels");
    expect(page.frameLocator(threePointPageObject.whole_Iframe).locator(threePointPageObject.edit_btn).nth(0)).toBeHidden();
    expect(page.frameLocator(threePointPageObject.whole_Iframe).locator(threePointPageObject.edit_btn).nth(1)).toBeHidden();
    expect(page.frameLocator(threePointPageObject.whole_Iframe).locator(threePointPageObject.edit_btn).nth(2)).toBeHidden();
    expect(page.frameLocator(threePointPageObject.whole_Iframe).locator(threePointPageObject.edit_btn).nth(3)).toBeHidden();
    expect(page.frameLocator(threePointPageObject.whole_Iframe).locator(threePointPageObject.graph_Heading).nth(2)).toBeVisible();
    expect(page.frameLocator(threePointPageObject.whole_Iframe).locator(threePointPageObject.graph_Heading).nth(2)).toHaveText("Price ($/pack)");
    expect(page.frameLocator(threePointPageObject.whole_Iframe).locator(threePointPageObject.graph_Heading).nth(3)).toBeVisible();
    expect(page.frameLocator(threePointPageObject.whole_Iframe).locator(threePointPageObject.graph_Heading).nth(3)).toHaveText("Quantity (1,000s of packs/day)");
    expect(page.frameLocator(threePointPageObject.whole_Iframe).locator(threePointPageObject.line_Sol)).toBeVisible();
expect(await threePointPageObject.getPolygonAttributeByLocator("stroke-width",threePointPageObject.line_Sol)).toEqual("2");
expect(await threePointPageObject.getPolygonAttributeByLocator("stroke",threePointPageObject.line_Sol)).toEqual("#00007f");
    
    await page.frameLocator(threePointPageObject.whole_Iframe).locator(threePointPageObject.attributes_Setup).nth(3).click();
    expect(page.frameLocator(threePointPageObject.whole_Iframe).locator(threePointPageObject.demand_txt)).toHaveText("Demand");
   expect(page.frameLocator(threePointPageObject.whole_Iframe).locator(threePointPageObject.d_txt)).toHaveText("D");
   expect(page.frameLocator(threePointPageObject.whole_Iframe).locator(threePointPageObject.edit_btn).nth(4)).toBeEnabled();
   expect(page.frameLocator(threePointPageObject.whole_Iframe).locator(threePointPageObject.edit_btn).nth(5)).toBeEnabled();
   expect(page.frameLocator(threePointPageObject.whole_Iframe).locator(threePointPageObject.lock_btn).nth(0)).toBeEnabled();
   expect(page.frameLocator(threePointPageObject.whole_Iframe).locator(threePointPageObject.lock_btn).nth(1)).toBeEnabled();
   expect(page.frameLocator(threePointPageObject.whole_Iframe).locator(threePointPageObject.delete_btn).nth(0)).toBeEnabled();
   expect(page.frameLocator(threePointPageObject.whole_Iframe).locator(threePointPageObject.delete_btn).nth(1)).toBeEnabled();
   await page.waitForTimeout(2000);
   await page.frameLocator(threePointPageObject.whole_Iframe).locator(threePointPageObject.attributes_Setup).nth(3).click();
   await page.frameLocator(threePointPageObject.whole_Iframe).locator(threePointPageObject.edit_btn).nth(4).click();
    expect(page.frameLocator(threePointPageObject.whole_Iframe).locator(threePointPageObject.line_Scoretxt)).toHaveText("Scoring:");
  expect(page.frameLocator(threePointPageObject.whole_Iframe).locator(threePointPageObject.radio_btn).nth(0)).toBeVisible();
  expect(page.frameLocator(threePointPageObject.whole_Iframe).locator(threePointPageObject.radio_btn).nth(0)).toBeChecked();
  expect(page.frameLocator(threePointPageObject.whole_Iframe).locator(threePointPageObject.radio_btn).nth(1)).toBeVisible();
  expect(page.frameLocator(threePointPageObject.whole_Iframe).locator(threePointPageObject.score_point).nth(0)).toHaveText("(2 pts)");
  expect(page.frameLocator(threePointPageObject.whole_Iframe).locator(threePointPageObject.score_point).nth(1)).toHaveText("(1 pts)");
  expect(page.frameLocator(threePointPageObject.whole_Iframe).locator(threePointPageObject.score_txt).nth(0)).toHaveText("Points");
  expect(page.frameLocator(threePointPageObject.whole_Iframe).locator(threePointPageObject.score_txt).nth(1)).toHaveText("Segments");
  expect(page.frameLocator(threePointPageObject.whole_Iframe).locator(threePointPageObject.line_Statetxt)).toHaveText("Line States:");
  expect(page.frameLocator(threePointPageObject.whole_Iframe).locator(threePointPageObject.radio_btn).nth(2)).toBeVisible();
  expect(page.frameLocator(threePointPageObject.whole_Iframe).locator(threePointPageObject.radio_btn).nth(2)).toBeChecked();
  expect(page.frameLocator(threePointPageObject.whole_Iframe).locator(threePointPageObject.radio_btn).nth(2)).toBeVisible();
  expect(page.frameLocator(threePointPageObject.whole_Iframe).locator(threePointPageObject.radio_btn).nth(2)).toHaveText("Solution View");
  expect(page.frameLocator(threePointPageObject.whole_Iframe).locator('.form-control').nth(0)).toHaveValue("0");
  expect(page.frameLocator(threePointPageObject.whole_Iframe).locator('.form-control').nth(1)).toHaveValue("6");
  expect(page.frameLocator(threePointPageObject.whole_Iframe).locator('.form-control').nth(2)).toHaveValue("3");
  expect(page.frameLocator(threePointPageObject.whole_Iframe).locator('.form-control').nth(3)).toHaveValue("5");
  expect(page.frameLocator(threePointPageObject.whole_Iframe).locator('.form-control').nth(4)).toHaveValue("6");
  expect(page.frameLocator(threePointPageObject.whole_Iframe).locator('.form-control').nth(5)).toHaveValue("4");
  expect(page.frameLocator(threePointPageObject.whole_Iframe).locator('.form-control').nth(6)).toHaveValue("9");
  expect(page.frameLocator(threePointPageObject.whole_Iframe).locator('.form-control').nth(7)).toHaveValue("3");
  expect(page.frameLocator(threePointPageObject.whole_Iframe).locator('.form-control').nth(8)).toHaveValue("12");
  expect(page.frameLocator(threePointPageObject.whole_Iframe).locator('.form-control').nth(9)).toHaveValue("2");
  expect(page.frameLocator(threePointPageObject.whole_Iframe).locator('.form-control').nth(10)).toHaveValue("15");
  expect(page.frameLocator(threePointPageObject.whole_Iframe).locator('.form-control').nth(11)).toHaveValue("1");
  expect(page.frameLocator(threePointPageObject.whole_Iframe).locator('.form-control').nth(12)).toHaveValue("18");
  expect(page.frameLocator(threePointPageObject.whole_Iframe).locator('.form-control').nth(13)).toHaveValue("0");
  await page.waitForTimeout(3000);
  expect(page.frameLocator(threePointPageObject.whole_Iframe).locator(threePointPageObject.add_Point).nth(0)).toBeVisible();
  expect(page.frameLocator(threePointPageObject.whole_Iframe).locator(threePointPageObject.add_Point).nth(0)).toBeEnabled();
  expect(page.frameLocator(threePointPageObject.whole_Iframe).locator(threePointPageObject.add_Point).nth(1)).toBeDisabled();
  expect(page.frameLocator(threePointPageObject.whole_Iframe).locator(threePointPageObject.add_Point).nth(2)).toBeDisabled();
  //expect(page.frameLocator(threePointPageObject.whole_Iframe).locator(threePointPageObject.add_Point).nth(0)).toHaveText("Add Point");
  expect(page.frameLocator(threePointPageObject.whole_Iframe).locator(threePointPageObject.draw_Compare).nth(0)).toBeDisabled();
  expect(page.frameLocator(threePointPageObject.whole_Iframe).locator(threePointPageObject.draw_Compare).nth(1)).toBeDisabled();  
  expect(page.frameLocator(threePointPageObject.whole_Iframe).locator(threePointPageObject.radio_btn).nth(3)).toBeVisible();   
  expect(page.frameLocator(threePointPageObject.whole_Iframe).locator(threePointPageObject.radio_btn).nth(3)).toHaveText("Question And Solution View");
  expect(page.frameLocator(threePointPageObject.whole_Iframe).locator('.form-control').nth(14)).toBeDisabled();
  expect(page.frameLocator(threePointPageObject.whole_Iframe).locator(threePointPageObject.foot_Print)).toBeDisabled(); 
  await page.frameLocator(threePointPageObject.whole_Iframe).locator(threePointPageObject.radio_btn).nth(3).click();
  expect(page.frameLocator(threePointPageObject.whole_Iframe).locator('.form-control').nth(14)).toBeEnabled();
  expect(page.frameLocator(threePointPageObject.whole_Iframe).locator('.form-control').nth(14)).toHaveValue("0");
  expect(page.frameLocator(threePointPageObject.whole_Iframe).locator('.form-control').nth(15)).toHaveValue("6");
  expect(page.frameLocator(threePointPageObject.whole_Iframe).locator('.form-control').nth(16)).toHaveValue("3");
  expect(page.frameLocator(threePointPageObject.whole_Iframe).locator('.form-control').nth(17)).toHaveValue("5");
  expect(page.frameLocator(threePointPageObject.whole_Iframe).locator('.form-control').nth(18)).toHaveValue("6");
  expect(page.frameLocator(threePointPageObject.whole_Iframe).locator('.form-control').nth(19)).toHaveValue("4");
  expect(page.frameLocator(threePointPageObject.whole_Iframe).locator('.form-control').nth(20)).toHaveValue("9");
  expect(page.frameLocator(threePointPageObject.whole_Iframe).locator('.form-control').nth(21)).toHaveValue("3");
  expect(page.frameLocator(threePointPageObject.whole_Iframe).locator('.form-control').nth(22)).toHaveValue("12");
  expect(page.frameLocator(threePointPageObject.whole_Iframe).locator('.form-control').nth(23)).toHaveValue("2");
  expect(page.frameLocator(threePointPageObject.whole_Iframe).locator('.form-control').nth(24)).toHaveValue("15");
  expect(page.frameLocator(threePointPageObject.whole_Iframe).locator('.form-control').nth(25)).toHaveValue("1");
  expect(page.frameLocator(threePointPageObject.whole_Iframe).locator('.form-control').nth(26)).toHaveValue("18");
  expect(page.frameLocator(threePointPageObject.whole_Iframe).locator('.form-control').nth(27)).toHaveValue("0");
  expect(page.frameLocator(threePointPageObject.whole_Iframe).locator(threePointPageObject.add_Point).nth(1)).toBeEnabled();
  expect(page.frameLocator(threePointPageObject.whole_Iframe).locator(threePointPageObject.Sol_View)).toBeVisible();
  expect(page.frameLocator(threePointPageObject.whole_Iframe).locator('.form-control').nth(28)).toHaveValue("0");
  expect(page.frameLocator(threePointPageObject.whole_Iframe).locator('.form-control').nth(29)).toHaveValue("6");
  expect(page.frameLocator(threePointPageObject.whole_Iframe).locator('.form-control').nth(30)).toHaveValue("3");
  expect(page.frameLocator(threePointPageObject.whole_Iframe).locator('.form-control').nth(31)).toHaveValue("5");
  expect(page.frameLocator(threePointPageObject.whole_Iframe).locator('.form-control').nth(32)).toHaveValue("6");
  expect(page.frameLocator(threePointPageObject.whole_Iframe).locator('.form-control').nth(33)).toHaveValue("4");
  expect(page.frameLocator(threePointPageObject.whole_Iframe).locator('.form-control').nth(34)).toHaveValue("9");
  expect(page.frameLocator(threePointPageObject.whole_Iframe).locator('.form-control').nth(35)).toHaveValue("3");
  expect(page.frameLocator(threePointPageObject.whole_Iframe).locator('.form-control').nth(36)).toHaveValue("12");
  expect(page.frameLocator(threePointPageObject.whole_Iframe).locator('.form-control').nth(37)).toHaveValue("2");
  expect(page.frameLocator(threePointPageObject.whole_Iframe).locator('.form-control').nth(38)).toHaveValue("15");
  expect(page.frameLocator(threePointPageObject.whole_Iframe).locator('.form-control').nth(39)).toHaveValue("1");
  expect(page.frameLocator(threePointPageObject.whole_Iframe).locator('.form-control').nth(40)).toHaveValue("18");
  expect(page.frameLocator(threePointPageObject.whole_Iframe).locator('.form-control').nth(41)).toHaveValue("0");
  expect(page.frameLocator(threePointPageObject.whole_Iframe).locator(threePointPageObject.add_Point).nth(2)).toBeEnabled();
  expect(page.frameLocator(threePointPageObject.whole_Iframe).locator(threePointPageObject.foot_Print)).toBeEnabled();
  await page.frameLocator(threePointPageObject.whole_Iframe).locator(threePointPageObject.cls_btn).click();
  await page.frameLocator(threePointPageObject.whole_Iframe).locator(threePointPageObject.edit_btn).nth(5).click();
  expect(page.frameLocator(threePointPageObject.whole_Iframe).locator(threePointPageObject.d_txt)).toHaveText("D");
  expect(page.frameLocator(threePointPageObject.whole_Iframe).locator('.form-control').nth(0)).toHaveValue("17");
 expect(page.frameLocator(threePointPageObject.whole_Iframe).locator('.form-control').nth(1)).toHaveValue("1");
 expect(page.frameLocator(threePointPageObject.whole_Iframe).locator(threePointPageObject.Label_txt)).toBeVisible();
 expect(page.frameLocator(threePointPageObject.whole_Iframe).locator(threePointPageObject.Label)).toBeVisible();
 expect(page.frameLocator(threePointPageObject.whole_Iframe).locator(threePointPageObject.Label)).toHaveText("Top Left");  
 expect(page.frameLocator(threePointPageObject.whole_Iframe).locator(threePointPageObject.graph_Label).nth(0)).toBeVisible();
 expect(page.frameLocator(threePointPageObject.whole_Iframe).locator(threePointPageObject.graph_Label).nth(0)).toHaveText("D");
  });